version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: LeaveLetterManagement
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: Backend
      dockerfile: ./dockerfile
    ports:
      - 5005:5005

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: UI
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  mongo_volume: